# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d199337d91ba41fdfb772678b13f19f0329b25a5fe4835e91af4c710c9e77ab6f707c2d3e6ec2d03c1e6e4dc7d34dfb6ae22abe5ce13d14b4cd0b544c222105

test:
  secret_key_base: 70ac41376ac6ddf38ff0f778fafcc5ef055dbde4052d0265995d90a67444eab213afc0d7f9d57b8462958200a397a8cf69fe8d488eed0f3e5c3c7b74039789a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
